# Generated by Django 5.1.7 on 2025-03-16 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0005_remove_employee_username_alter_employee_department'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='employee',
            managers=[
            ],
        ),
    ]
